Arduino Digital Write `<http://arduino.cc/en/Reference/DigitalWrite>`_

================ ================================ ==================
Setting          Value                            Value
================ ================================ ==================
Library          BuiltIn                          \
Library          DigitalWrite.py                  \
Test Setup       Compile Flash Code               ${setupFlag}      
Test Teardown    Clean Code                       ${teardownFlag}
================ ================================ ==================

============== ============= =============
Variable       Value         Value
============== ============= =============
\              \             \
============== ============= =============

==================== ================== ================== ==========================
Test Case            Action             Argument           Argument         
==================== ================== ================== ==========================
Write high to pin    [Documentation]    Test Setup:        Test Case: Check state        
                                        Compile the code.  of pin as 'HIGH' through
                                        Test Teardown:     logical analyzer.
                                        Clean the code.    \
\                    [Setup]            Compile Flash Code High
\                    Write High         \                  \
\                    [Teardown]         Clean Code         High
\                    \                  \                  \
Write low to pin     [Documentation]    Test Setup:        Test Case: Check state        
                                        Compile the code.  of pin as 'LOW' through
                                        Test Teardown:     logical analyzer.
                                        Clean the code.    \
\                    [Setup]            Compile Flash Code Low
\                    Write Low          \                  \
\                    [Teardown]         Clean Code         Low        
==================== ================== ================== ==========================
