Arduino Digital Read `<http://arduino.cc/en/Reference/DigitalRead>`_

================ ============================== =================== 
Setting          Value							Value               
================ ============================== =================== 
Library          BuiltIn                        \                   
Library          DigitalRead.py                 \                   
Test Setup       Compile Flash Code             ${setupFlag}      
Test Teardown    Clean Code                     ${teardownFlag}
================ ============================== =================== 

============== =================== ===================
Variable       Value               Value
============== =================== ===================
\              \                   \
============== =================== ===================

==================== ================== ================== =========================
Test Case            Action             Argument           Argument                 
==================== ================== ================== =========================
Read high from pin   [Documentation]    Test Setup:        Test Case: Check state        
                                        Compile the code.  of pin as 'HIGH' through
                                        Test Teardown:     logical analyzer.
                                        Clean the code.    \
\                    [Setup]            Compile Flash Code High
\                    Read High          \                  \
\                    [Teardown]         Clean Code         High
\                    \                  \                  \
Read low from pin    [Documentation]    Test Setup:        Test Case: Check state        
                                        Compile the code.  of pin as 'LOW' through
                                        Test Teardown:     logical analyzer.
                                        Clean the code.    \
\                    [Setup]            Compile Flash Code Low
\                    Read Low           \                  \
\                    [Teardown]         Clean Code         Low 
==================== ================== ================== =========================
