Arduino Time Delay `<http://arduino.cc/en/Reference/Delay>`_

================ ============================
    Setting          Value
================ ============================
Library          BuiltIn
Library          ${TESTPATH}/TimeDelay.py
Test Setup       \          
Test Teardown    \         
================ ============================

================== =============
    Variable       Value
================== =============
${PIN}             ${0}
${HIGH}            ${true}
${LOW}             ${false}
${TIME}            ${0}
================== =============

=============================== =================== ================= ================
    Test Case                   Action              Argument          Argument
=============================== =================== ================= ================
\                               \                   \                 \
=============================== =================== ================= ================




============= ================= ============== ==============
   Keyword    \                 \              \
============= ================= ============== ==============
\             \                 \              \
============= ================= ============== ==============
