Arduino Digital Write `<http://arduino.cc/en/Reference/DigitalWrite>`_

================ ================================ ==================
Setting          Value                            Value
================ ================================ ==================
Library          BuiltIn                          \
Library          DigitalWrite.py                  \
Test Setup       Set Pin Mode					  @{args}
Test Teardown    NONE                             \
================ ================================ ==================

============== ============= =============
Variable       Value         Value
============== ============= =============
${PORT}=       A             \
${PIN}=        ${2}          \
@{args}=       ${PORT}       ${PIN}
============== ============= =============

==================== ================== ================== ==========================
Test Case            Action             Argument           Argument
==================== ================== ================== ==========================
Write high to pin    [Documentation]    Test Setup:        Test Case: Change state
                                        Set the pin mode   of pin to 'HIGH'.
                                        to output.         \
\                    Write High         ${PORT}            ${PIN}
\
Write low to pin     [Documentation]    Test Setup:        Test Case: Change state
                                        Set the pin mode   of pin to 'LOW'.
                                        to output.         \
\                    Write Low          ${PORT}            ${PIN}
==================== ================== ================== ==========================
