Arduino Pin Mode `<http://arduino.cc/en/Reference/PinMode>`_

============== ==========================
Setting        Value
============== ==========================
Library        BuiltIn
Library        PinMode.py
Test Setup     \
Test Teardown  \
============== ==========================

================= =========
Variable          Value
================= =========
${PORT}=          A
${PIN}=           ${2}
================= =========

=========================== ==================== ================== ===========================
Test Case                   Action               Argument           Argument
=========================== ==================== ================== ===========================
Set input pin mode          [Documentation]      Logs setting of    input pin mode
\                           Input Pin Mode       ${PORT}            ${PIN}
\
Set output pin mode         [Documentation]      Logs setting of    output pin mode
\                           Output Pin Mode      ${PORT}            ${PIN}
\
Set input pullup mode       [Documentation]      Logs setting of    input pin pullup mode
\                           Input Pullup Mode    ${PORT}            ${PIN}
=========================== ==================== ================== ===========================
